# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ecbef322e3f8b1aee333f0164f721f269e8f9ee6f6f4c3e690cf9243a8c72ad7308ca6214c655eab3bb3d53b9975cecd6b488e45da2b0dc9ff56f79862d0b673

test:
  secret_key_base: 8ce360e566e7b50c8dbb2c74fd466d56e210eb0749c33f9893c2033d14d0019a12fd0fcc61c05118ce154ffd101bfd2b89ec8d4b5bf4c72a6c395789feca3fff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
